[package]
name = "irc_core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
tokio = {version = "1.48.0", features = ["full", "io-util"]}
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
