[alias]
bot = ["run", "-p", "bot", "--",
       "--server", "localhost:6667",
       "--nick", "rustobotato",
       "--user", "tobotato"]

ircd = "exec /Users/wonderzombie/src/miniircd/miniircd --verbose"

